# Generated by Django 3.2.12 on 2022-05-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_delete_statusandrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('cust_name', models.CharField(max_length=120)),
                ('cust_shortname', models.CharField(blank=True, max_length=120)),
                ('tax_identification_no', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('brgy', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=120)),
                ('customer_group', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter')),
                ('default_pricelist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricelist')),
                ('default_receivable_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccounts')),
                ('vat_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.vatgroup')),
                ('wht', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.withholdingtaxgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDiscounts',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selling.customer')),
                ('discount_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.discountgroup')),
            ],
        ),
    ]
