# Generated by Django 3.2.12 on 2022-03-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('fixed_asset_name', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('sku_code', models.CharField(max_length=120)),
                ('item_barcode', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=120)),
                ('item_shortname', models.CharField(max_length=120)),
                ('is_fixed_asset', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('maintain_stock', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('serial_no', models.CharField(blank=True, max_length=120)),
                ('batch_no', models.CharField(blank=True, max_length=120)),
                ('expiry', models.DateField(blank=True)),
                ('is_purchase_item', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('is_sales_item', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('item_group_name', models.CharField(max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('uom', models.CharField(max_length=120)),
                ('must_be_a_whole_number', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOMConversionDetail',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('conversion_factor', models.FloatField()),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.uom')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricelist')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='base_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, to='stock.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_cos_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_cos_account', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_income_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_income_account', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='item',
            name='fixed_asset_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_asset_group', to='stock.itemgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(default='Product', on_delete=django.db.models.deletion.CASCADE, related_name='item_group', to='stock.itemgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_uom', to='stock.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, related_name='sales_uom', to='stock.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='vat_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vat_group', to='accounting.vatgroup'),
        ),
    ]
