# Generated by Django 3.2.12 on 2022-03-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20220321_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
