# Generated by Django 3.2.12 on 2022-03-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_itemprice_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.item'),
        ),
    ]
