# Generated by Django 4.0.5 on 2022-08-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_itemcatbrand_itemcatdepartment_itemcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
