# Generated by Django 4.1.1 on 2022-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_itemgroup_code_alter_uom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
