# Generated by Django 3.2.9 on 2022-01-19 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=120)),
                ('account_type_and_financial_group', models.CharField(max_length=80)),
                ('normal_balance', models.CharField(max_length=120)),
                ('report', models.CharField(max_length=120)),
                ('is_default_expense', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=120)),
                ('company_shortname', models.CharField(max_length=120)),
                ('company_address', models.CharField(max_length=120, null=True)),
                ('company_contact_no', models.CharField(max_length=120, null=True)),
                ('company_email', models.CharField(max_length=120, null=True)),
                ('is_group', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('company_group', models.CharField(max_length=120, null=True)),
                ('currency', models.CharField(default='PHP', max_length=4)),
                ('company_reg_no', models.CharField(max_length=120, null=True)),
                ('company_taxid_no', models.CharField(max_length=120, null=True)),
                ('business_permit_no', models.CharField(max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cost_center_code', models.CharField(max_length=120)),
                ('cost_center_name', models.CharField(max_length=120)),
                ('cost_center_shortname', models.CharField(max_length=120)),
                ('is_group', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('cost_center_group', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedDocuments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=120)),
                ('id_no', models.CharField(blank=True, max_length=120)),
                ('object', models.CharField(blank=True, max_length=5000)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAssetGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=120)),
                ('sku_code', models.CharField(max_length=120)),
                ('item_barcode', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=120)),
                ('item_shortname', models.CharField(max_length=120)),
                ('item_group', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_brand', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_department', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_category', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_form', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatManufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_manufacturer', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_section', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_size', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('is_buying', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('is_selling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('is_both', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('current', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusAndRCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_group', models.CharField(max_length=120)),
                ('module', models.CharField(max_length=120)),
                ('sub_module', models.CharField(max_length=120)),
                ('trans_type', models.CharField(max_length=120)),
                ('trans_label', models.CharField(max_length=120)),
                ('trans_label_shortname', models.CharField(max_length=120)),
                ('trans_trigger', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('uom', models.CharField(max_length=120)),
                ('must_be_a_whole_number', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VatGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('vat_group_code', models.CharField(max_length=120)),
                ('vat_group_name', models.CharField(max_length=120)),
                ('rate', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithHoldingTaxGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('wht_code', models.CharField(max_length=120)),
                ('wht_name', models.CharField(max_length=120)),
                ('rate', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOMConversionFactor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversion_factor', models.FloatField()),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uom')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('sup_code', models.CharField(max_length=120)),
                ('sup_name', models.CharField(max_length=120)),
                ('sup_shortname', models.CharField(blank=True, max_length=120)),
                ('check_payee_name', models.CharField(blank=True, max_length=120)),
                ('is_trucker', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('tax_identification_no', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('brgy', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.costcenter')),
                ('default_expense_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.chartofaccounts')),
                ('default_pricelist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.pricelist')),
                ('discount_group1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount1', to='api.discountgroup')),
                ('discount_group2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount2', to='api.discountgroup')),
                ('discount_group3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discou', to='api.discountgroup')),
                ('supplier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suppliergroup')),
                ('vat_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.vatgroup')),
                ('wht', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.withholdingtaxgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=120)),
                ('location_name', models.CharField(max_length=120)),
                ('location_shortname', models.CharField(max_length=120)),
                ('is_group', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('branch_group', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=45)),
                ('branch_name', models.CharField(max_length=45)),
                ('branch_shortname', models.CharField(max_length=45)),
                ('is_group', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('company_group', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('acctng_period_code', models.CharField(max_length=45)),
                ('acctng_period_name', models.CharField(max_length=45)),
                ('acctng_period_start_date', models.DateField()),
                ('acctng_period_end_date', models.DateField()),
                ('status', models.CharField(default='Open', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
