# Generated by Django 3.2.9 on 2022-01-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=120)),
                ('account_type_and_financial_group', models.CharField(max_length=80)),
                ('normal_balance', models.CharField(max_length=120)),
                ('report', models.CharField(max_length=120)),
                ('is_default_expense', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=120)),
                ('company_shortname', models.CharField(max_length=120)),
                ('company_address', models.CharField(max_length=120, null=True)),
                ('company_contact_no', models.CharField(max_length=120, null=True)),
                ('company_email', models.CharField(max_length=120, null=True)),
                ('is_group', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('company_group', models.CharField(max_length=120, null=True)),
                ('currency', models.CharField(default='PHP', max_length=4)),
                ('company_reg_no', models.CharField(max_length=120, null=True)),
                ('company_taxid_no', models.CharField(max_length=120, null=True)),
                ('business_permit_no', models.CharField(max_length=120, null=True)),
                ('is_construction_company', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('cost_center_code', models.CharField(max_length=120)),
                ('cost_center_name', models.CharField(max_length=120)),
                ('cost_center_shortname', models.CharField(max_length=120)),
                ('is_group', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('cost_center_group', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedDocuments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=120)),
                ('id_no', models.CharField(blank=True, max_length=120)),
                ('object', models.CharField(blank=True, max_length=5000)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=120)),
                ('discount1', models.FloatField(max_length=120)),
                ('discount2', models.FloatField(max_length=120)),
                ('discount3', models.FloatField(max_length=120)),
                ('total_discount', models.FloatField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAssetGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=120)),
                ('sku_code', models.CharField(max_length=120)),
                ('item_barcode', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=120)),
                ('item_shortname', models.CharField(max_length=120)),
                ('is_fixed_asset', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('maintain_stock', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('serial_no', models.CharField(blank=True, max_length=120)),
                ('batch_no', models.CharField(blank=True, max_length=120)),
                ('expiry', models.DateField(blank=True)),
                ('is_purchase_item', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('is_sales_item', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_brand', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_department', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_category', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_form', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatManufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_manufacturer', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_section', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_size', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('is_buying', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('is_selling', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('is_transfer', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('no_of_zeroes', models.IntegerField(default=5)),
                ('current', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusAndRCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_group', models.CharField(max_length=120)),
                ('module', models.CharField(max_length=120)),
                ('sub_module', models.CharField(max_length=120)),
                ('trans_type', models.CharField(max_length=120)),
                ('trans_label', models.CharField(max_length=120)),
                ('trans_label_shortname', models.CharField(max_length=120)),
                ('trans_trigger', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('sup_code', models.CharField(max_length=120)),
                ('sup_name', models.CharField(max_length=120)),
                ('sup_shortname', models.CharField(blank=True, max_length=120)),
                ('check_payee_name', models.CharField(blank=True, max_length=120)),
                ('is_trucker', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('tax_identification_no', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('brgy', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.costcenter')),
                ('default_expense_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_expense_account', to='api.chartofaccounts')),
                ('default_payable_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_payable_account', to='api.chartofaccounts')),
                ('default_pricelist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.pricelist')),
                ('discount_group1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_group1', to='api.discountgroup')),
                ('discount_group2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_group2', to='api.discountgroup')),
                ('discount_group3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_group3', to='api.discountgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('uom', models.CharField(max_length=120)),
                ('must_be_a_whole_number', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VatGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('vat_group_code', models.CharField(max_length=120)),
                ('vat_group_name', models.CharField(max_length=120)),
                ('rate', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithHoldingTaxGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('wht_code', models.CharField(max_length=120)),
                ('wht_name', models.CharField(max_length=120)),
                ('rate', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOMConversionDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversion_factor', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uom')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suppliergroup'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.vatgroup'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='wht',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.withholdingtaxgroup'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=120)),
                ('location_name', models.CharField(max_length=120)),
                ('location_shortname', models.CharField(max_length=120)),
                ('is_group', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('branch_group', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uom')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pricelist')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='base_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, to='api.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_cos_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_cos_account', to='api.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_income_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_income_account', to='api.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='item',
            name='fixed_asset_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_asset_group', to='api.itemgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(default='Product', on_delete=django.db.models.deletion.CASCADE, related_name='item_group', to='api.itemgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_uom', to='api.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, related_name='sales_uom', to='api.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='vat_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vat_group', to='api.vatgroup'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discountgroup',
            name='base_uom',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.uom'),
        ),
        migrations.AddField(
            model_name='discountgroup',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=45)),
                ('branch_name', models.CharField(max_length=45)),
                ('branch_shortname', models.CharField(max_length=45)),
                ('is_group', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('company_group', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('acctng_period_code', models.CharField(max_length=45)),
                ('acctng_period_name', models.CharField(max_length=45)),
                ('acctng_period_start_date', models.DateField()),
                ('acctng_period_end_date', models.DateField()),
                ('status', models.CharField(default='Open', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
