# Generated by Django 3.2.9 on 2022-01-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_cos_account',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='default_cos_account', to='api.chartofaccounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='default_income_account',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='default_income_account', to='api.chartofaccounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_prices',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_uom', to='api.uom'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_item',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_uom',
            field=models.ForeignKey(default='Unit', on_delete=django.db.models.deletion.CASCADE, related_name='sales_uom', to='api.uom'),
        ),
        migrations.AddField(
            model_name='series',
            name='no_of_zeroes',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('is_default_selling', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('is_default_buying', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uom')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pricelist')),
            ],
        ),
    ]
