# Generated by Django 3.2.9 on 2021-12-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='coa_group',
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_type_and_financial_group',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
