# Generated by Django 3.2.9 on 2022-01-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountgroup',
            name='base_uom',
        ),
        migrations.RemoveField(
            model_name='discountgroup',
            name='item',
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='discount1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='discount2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='discount3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='total_discount',
            field=models.FloatField(),
        ),
    ]
