# Generated by Django 3.2.9 on 2022-01-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220129_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='wht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.withholdingtaxgroup'),
        ),
    ]
