# Generated by Django 3.2.9 on 2022-01-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220122_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='conversion_detail',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_prices',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier_items',
        ),
        migrations.CreateModel(
            name='SupplierItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
    ]
