# Generated by Django 3.2.9 on 2022-01-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220122_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='purchase_item',
            new_name='is_purchase_item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sales_item',
            new_name='is_sales_item',
        ),
    ]
