# Generated by Django 3.2.9 on 2021-12-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chartofaccounts_is_default_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_group',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='is_default_expense',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_group',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='is_group',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_group',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
    ]
