# Generated by Django 3.2.9 on 2022-01-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_supplier_wht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='default_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_expense_account', to='api.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_payable_account', to='api.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_pricelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pricelist'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_group1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_group1', to='api.discountgroup'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_group2', to='api.discountgroup'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_group3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_group3', to='api.discountgroup'),
        ),
    ]
