# Generated by Django 3.2.9 on 2021-12-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_accountingperiod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingperiod',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_code',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='is_default_expense',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='normal_balance',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='report',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_permit_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_contact_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_group',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_reg_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_shortname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_taxid_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_code',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_group',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_shortname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='branch_group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_code',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_shortname',
            field=models.CharField(max_length=120),
        ),
    ]
