# Generated by Django 3.2.9 on 2021-12-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211226_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_group',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
    ]
