# Generated by Django 3.2.9 on 2021-12-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_is_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_brand', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_department', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_category', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_form', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatManufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_manufacturer', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_section', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_size', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('uom', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('must_be_a_whole_number', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
