# Generated by Django 3.2.9 on 2022-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220130_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
