# Generated by Django 3.2.9 on 2021-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211225_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusandrcode',
            name='module',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='module_group',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='remarks',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='sub_module',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='trans_label',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='trans_label_shortname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='trans_trigger',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='trans_type',
            field=models.CharField(max_length=120),
        ),
    ]
