# Generated by Django 3.2.9 on 2021-12-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211225_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingperiod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
    ]
