# Generated by Django 3.2.9 on 2021-12-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_itemcatbrand_itemcatdepartment_itemcategory_itemcatform_itemcatmanufacturer_itemcatsection_itemcatsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('vat_group_code', models.CharField(max_length=120)),
                ('vat_group_name', models.CharField(max_length=120)),
                ('vat_rate', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
