# Generated by Django 3.2.9 on 2022-02-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
