# Generated by Django 3.2.9 on 2022-02-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
