# Generated by Django 3.2.9 on 2022-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vatgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithHoldingTaxGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('wht_code', models.CharField(max_length=120)),
                ('wht_name', models.CharField(max_length=120)),
                ('rate', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vatgroup',
            old_name='vat_rate',
            new_name='rate',
        ),
    ]
