# Generated by Django 3.2.9 on 2022-01-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220105_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('current', models.IntegerField(max_length=120)),
            ],
        ),
    ]
