# Generated by Django 3.2.9 on 2022-01-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='current',
            field=models.IntegerField(),
        ),
    ]
