# Generated by Django 3.2.9 on 2022-01-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_system_current'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System',
            new_name='Series',
        ),
    ]
