# Generated by Django 3.2.9 on 2022-02-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220206_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='discount_group1',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='discount_group2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='discount_group3',
        ),
        migrations.CreateModel(
            name='SupplierDiscounts',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discountgroup')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
    ]
