# Generated by Django 3.2.9 on 2022-01-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_system_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('is_buying', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('is_selling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('is_both', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='statusandrcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statusandrcode',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='statusandrcode',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcatbrand',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcatdepartment',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcatform',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcatmanufacturer',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcatsection',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcatsize',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vatgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='withholdingtaxgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('sup_code', models.CharField(max_length=120)),
                ('sup_name', models.CharField(max_length=120)),
                ('sup_shortname', models.CharField(blank=True, max_length=120)),
                ('check_payee_name', models.CharField(blank=True, max_length=120)),
                ('is_trucker', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('tax_identification_no', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('brgy', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True)),
                ('cost_center', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.costcenter')),
                ('default_expense_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.chartofaccounts')),
                ('default_pricelist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.pricelist')),
                ('discount_group1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount1', to='api.discountgroup')),
                ('discount_group2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount2', to='api.discountgroup')),
                ('discount_group3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discou', to='api.discountgroup')),
                ('supplier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suppliergroup')),
                ('vat_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.vatgroup')),
                ('wht', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.withholdingtaxgroup')),
            ],
        ),
    ]
