# Generated by Django 3.2.9 on 2022-02-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220225_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdiscounts',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
