# Generated by Django 3.2.9 on 2022-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_supplierdiscounts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCompany',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
    ]
