# Generated by Django 3.2.9 on 2022-03-04 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_parentcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedassetgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AddField(
            model_name='fixedassetgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
