# Generated by Django 3.2.9 on 2022-01-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=120),
            preserve_default=False,
        ),
    ]
