# Generated by Django 3.2.9 on 2022-03-04 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220304_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AddField(
            model_name='pricelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statusandrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AddField(
            model_name='statusandrcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
