# Generated by Django 3.2.9 on 2022-03-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220304_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
    ]
