# Generated by Django 3.2.9 on 2022-01-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_domain_name_domain_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingperiod',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemcatbrand',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemcatdepartment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemcatform',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemcatmanufacturer',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemcatsection',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemcatsize',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='uom',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='vatgroup',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='withholdingtaxgroup',
            name='deleted_at',
        ),
    ]
