# Generated by Django 3.2.9 on 2022-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220113_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company_group',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
