# Generated by Django 3.2.9 on 2022-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_branch_company_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='uom',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='uom',
            name='id',
            field=models.CharField(default='Unit', max_length=120, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
