# Generated by Django 4.0.5 on 2022-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(default='EMP_{9}', max_length=120),
        ),
    ]
