# Generated by Django 3.2.12 on 2022-03-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=45)),
                ('branch_name', models.CharField(max_length=45)),
                ('branch_shortname', models.CharField(max_length=45)),
                ('is_group', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedDocuments',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=120)),
                ('id_no', models.CharField(blank=True, max_length=120)),
                ('object', models.CharField(blank=True, max_length=5000)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCompany',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('parent_company_name', models.CharField(max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('no_of_zeroes', models.IntegerField(default=5)),
                ('current', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('location_name', models.CharField(max_length=120)),
                ('location_shortname', models.CharField(max_length=120)),
                ('is_group', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('company_shortname', models.CharField(max_length=120)),
                ('company_address', models.CharField(max_length=120, null=True)),
                ('company_contact_no', models.CharField(max_length=120, null=True)),
                ('company_email', models.CharField(max_length=120, null=True)),
                ('is_group', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('currency', models.CharField(default='PHP', max_length=4)),
                ('company_reg_no', models.CharField(max_length=120, null=True)),
                ('company_taxid_no', models.CharField(max_length=120, null=True)),
                ('business_permit_no', models.CharField(max_length=120, null=True)),
                ('is_construction_company', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.parentcompany')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='company_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.company'),
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=45)),
                ('acctng_period_name', models.CharField(blank=True, max_length=45)),
                ('acctng_period_start_date', models.DateField(blank=True)),
                ('acctng_period_end_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=45)),
                ('jan', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('feb', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('mar', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('apr', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('may', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('jun', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('jul', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('aug', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('sep', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('oct', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('nov', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('dec', models.IntegerField(choices=[(1, 1), (0, 0)], default=1)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.company')),
            ],
        ),
    ]
