# Generated by Django 4.0.5 on 2022-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_statusandrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingperiod',
            name='code',
            field=models.CharField(default='ACC-PRD_{5}', max_length=45),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(default='BR_{9}', max_length=45),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='COMP_{9}', max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(default='LOC_{9}', max_length=120),
        ),
        migrations.AlterField(
            model_name='parentcompany',
            name='code',
            field=models.CharField(default='PRNT-COMP_{5}', max_length=120),
        ),
        migrations.AlterField(
            model_name='statusandrcode',
            name='code',
            field=models.CharField(default='RC_{9}', max_length=120),
        ),
    ]
