# Generated by Django 3.2.12 on 2022-03-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_discountgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('sup_name', models.CharField(max_length=120)),
                ('sup_shortname', models.CharField(blank=True, max_length=120)),
                ('check_payee_name', models.CharField(blank=True, max_length=120)),
                ('is_trucker', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('tax_identification_no', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('brgy', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter')),
                ('default_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_expense_account', to='accounting.chartofaccounts')),
                ('default_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_payable_account', to='accounting.chartofaccounts')),
                ('default_pricelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricelist')),
                ('supplier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.suppliergroup')),
                ('vat_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.vatgroup')),
                ('wht', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.withholdingtaxgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDiscounts',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.discountgroup')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buying.supplier')),
            ],
        ),
    ]
