# Generated by Django 3.2.12 on 2022-03-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_discountgroup'),
        ('buying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdiscounts',
            name='brgy',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='check_payee_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='cost_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='default_expense_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_account', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='default_payable_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payable_account', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='default_pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricelist'),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='email',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='is_trucker',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=0),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='phone',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='postal_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='street',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='sup_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='sup_shortname',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='supplier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.suppliergroup'),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='tax_identification_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='term',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='vat_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.vatgroup'),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='wht',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.withholdingtaxgroup'),
        ),
    ]
