# Generated by Django 3.2.12 on 2022-03-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0002_auto_20220322_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='discount_group',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='supplier',
        ),
    ]
