# Generated by Django 3.2.12 on 2022-03-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_discountgroup'),
        ('buying', '0003_auto_20220322_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='brgy',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='check_payee_name',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='default_expense_account',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='default_payable_account',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='default_pricelist',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='is_trucker',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='province',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='street',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='sup_name',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='sup_shortname',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='supplier_group',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='tax_identification_no',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='term',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='vat_group',
        ),
        migrations.RemoveField(
            model_name='supplierdiscounts',
            name='wht',
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='discount_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.discountgroup'),
        ),
        migrations.AddField(
            model_name='supplierdiscounts',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buying.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cost_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_expense_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_account', to='accounting.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_payable_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payable_account', to='accounting.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricelist'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.suppliergroup'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.vatgroup'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='wht',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.withholdingtaxgroup'),
        ),
    ]
