# Generated by Django 4.0.5 on 2022-08-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0005_purchaseorder_poitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitems',
            name='code',
            field=models.CharField(blank=True, default='PO-ITM_{10}', max_length=120),
        ),
    ]
