# Generated by Django 4.0.5 on 2022-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0006_alter_poitems_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='code',
            field=models.CharField(default='PO_{7}', max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(default='SUP_{9}', max_length=120),
        ),
        migrations.AlterField(
            model_name='supplierdiscounts',
            name='code',
            field=models.CharField(default='SUP-DISC_{9}', max_length=120),
        ),
    ]
