# Generated by Django 4.0.5 on 2022-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0007_alter_purchaseorder_code_alter_supplier_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitems',
            name='item_code',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
