# Generated by Django 4.1.1 on 2022-10-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0008_poitems_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitems',
            name='net_purchase_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
