# Generated by Django 4.1.1 on 2022-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0010_rename_qty_ordered_poitems_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poitems',
            old_name='net_purchase_rate',
            new_name='amount_payable',
        ),
        migrations.AddField(
            model_name='poitems',
            name='gross_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poitems',
            name='net_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poitems',
            name='vat_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
