# Generated by Django 4.1.1 on 2023-01-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0012_alter_poitems_amount_alter_poitems_amount_payable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poitems',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='poitems',
            old_name='uom',
            new_name='uom_id',
        ),
    ]
