# Generated by Django 4.1.1 on 2023-01-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0014_rename_item_id_poitems_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poitems',
            old_name='item_description',
            new_name='item_name',
        ),
    ]
