# Generated by Django 4.1.1 on 2023-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0015_rename_item_description_poitems_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='docstatus',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
