# Generated by Django 4.1.1 on 2023-03-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0016_purchaseorder_docstatus_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='docstatus',
            field=models.IntegerField(default=0),
        ),
    ]
