# Generated by Django 4.1.1 on 2023-03-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_accountingperiod_code_alter_branch_code_and_more'),
        ('stock', '0011_alter_itemprice_rate'),
        ('accounting', '0014_alter_pricingrule_criteria_amt_and_more'),
        ('buying', '0017_alter_purchaseorder_docstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReceipt',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(default='IR_{7}', max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_expected', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('apply_tax', models.CharField(choices=[(1, 1), (0, 0)], default=0, max_length=1)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('docstatus', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.branch')),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter')),
                ('fixed_asset_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.fixedassetgroup')),
                ('item_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.itemgroup')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.location')),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricelist')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buying.purchaseorder')),
                ('reason_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.statusandrcode')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buying.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='IRItems',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='IR-ITM_{10}', max_length=120)),
                ('has_uom_variance', models.CharField(choices=[(1, 1), (0, 0)], default=0, max_length=1)),
                ('item_code', models.CharField(blank=True, max_length=120)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('item_shortname', models.CharField(blank=True, max_length=120)),
                ('qty_ordered', models.FloatField(default=0, max_length=10)),
                ('qty_received', models.FloatField(default=0, max_length=10)),
                ('qty_over', models.FloatField(default=0, max_length=10)),
                ('uom_name', models.CharField(blank=True, max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('item_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buying.itemreceipt')),
                ('price_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.pricingrule')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.uom')),
                ('vat_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.vatgroup')),
            ],
        ),
    ]
