# Generated by Django 4.0.4 on 2022-04-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_discountgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusAndRCode',
        ),
    ]
