# Generated by Django 3.2.13 on 2022-05-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0004_auto_20220322_1625'),
        ('stock', '0005_supplieritem_item'),
        ('setup', '0002_statusandrcode'),
        ('accounting', '0003_delete_statusandrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('price_rule_name', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('apply_for', models.CharField(choices=[('Buying', 'Buying'), ('Selling', 'Selling')], default='Buying', max_length=10)),
                ('criteria_qty', models.FloatField(default=0)),
                ('criteria_amt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('criteria_prd_start', models.DateField(blank=True)),
                ('criteria_prd_end', models.DateField(blank=True)),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_amt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.branch')),
                ('criteria_uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.uom')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.location')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyTo',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('pricing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.pricingrule')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buying.supplier')),
            ],
        ),
    ]
