# Generated by Django 3.2.13 on 2022-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_applyto_pricingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='criteria_prd_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='criteria_prd_start',
            field=models.DateField(null=True),
        ),
    ]
