# Generated by Django 4.0.5 on 2022-08-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_discountgroup_discount1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyto',
            name='code',
            field=models.CharField(default='APLY-PRC-RLE_{9}', max_length=120),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='criteria_amt',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
