# Generated by Django 4.1.1 on 2022-10-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_itemgroup_code_alter_uom_code'),
        ('accounting', '0008_alter_chartofaccounts_code_alter_costcenter_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountItems',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(default='DISC-ITMS_{9}', max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disc_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.discountgroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
            ],
        ),
    ]
