# Generated by Django 4.1.1 on 2022-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_discountitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRate',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('code', models.CharField(default='DISC-RATE_{9}', max_length=120)),
                ('disc_rate', models.FloatField()),
                ('disc_name', models.CharField(max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='discountgroup',
            name='total_discount',
            field=models.FloatField(default=0),
        ),
    ]
