# Generated by Django 4.1.1 on 2022-10-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_discountrate_alter_discountgroup_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrate',
            name='disc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.discountgroup'),
        ),
    ]
