# Generated by Django 4.1.1 on 2022-10-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_discountrate_disc_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountgroup',
            name='discounts',
        ),
    ]
